// generated by `sqlx migrate build-script`
fn main() {
    let mut compiler = capnpc::CompilerCommand::new();

    compiler
        .src_prefix("capnp") // Directorio fuente donde están los archivos .capnp
        .file("capnp/car_motion.capnp")
        .file("capnp/event_data.capnp")
        .file("capnp/final_classification.capnp")
        .file("capnp/participants.capnp")
        .file("capnp/session_data.capnp")
        .file("capnp/session_history.capnp")
        .file("capnp/packet_header.capnp")
        // .output_path("src/capnp")
        .default_parent_module(vec!["capnp".to_string()])
        .run()
        .expect("compiling schema");
}
