// generated by `sqlx migrate build-script`
fn main() {
    println!("OUT_DIR: {}", std::env::var("OUT_DIR").unwrap());

    prost_build::compile_protos(
        &[
            "protos/car_motion.proto",
            "protos/event_data.proto",
            "protos/final_classification.proto",
            "protos/participants.proto",
            "protos/session_data.proto",
            "protos/session_history.proto",
        ],
        &["protos/"],
    )
    .unwrap();
}
