[package]
name = "intelli-api"
edition = "2021"
version = "0.6.3"
readme = "README.md"
description = "F1 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
repository = "https://github.com/Intelli-Telemetry/api"

[dependencies]
memchr = "2"
serde_trim = "1"
postgres-derive = "0.4"
deadpool-postgres = "0.14"
tokio = { version = "1", features = ["full"] }
regex = { version = "1", features = ["unstable"] }
chrono = { version = "0.4", features = ["serde"] }
openssl = { version = "0.10", features = ["v110"] }
serde = { version = "1", features = ["rc", "unstable"] }
dashmap = { version = "6", features = ["inline", "raw-api"] }
postgres-types = { version = "0.2", features = ["with-chrono-0_4"] }
mimalloc = { version = "0.1", features = [
    "extended",
    "local_dynamic_tls",
    "override",
] }

lettre = { version = "0.11", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
    "pool",
] }

[profile.release]
debug = false
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
