[package]
name = "token"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
base64-simd = { workspace = true }

[lints]
workspace = true
