[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
error = { path = "../error" }

serde = { workspace = true }
parking_lot = { workspace = true }
postgres-types = { workspace = true }
