[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
path = "src/utils.rs"
doctest = false

[dependencies]
error.workspace = true
serde.workspace = true
parking_lot.workspace = true
postgres-types.workspace = true
