[package]
name = "id-generator"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
path = "src/id_generator.rs"
doctest = false

[dependencies]
ring.workspace = true
ahash.workspace = true
parking_lot.workspace = true
