[package]
name = "error"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
sailfish = { workspace = true }
deadpool-postgres = { workspace = true }

[lints]
workspace = true
